export const commonProducts = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 10.99,
    rating: 4.5,
    genre: "Fiction",
    description: "A classic novel about racial injustice.",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    price: 8.99,
    rating: 4.8,
    genre: "Dystopian",
    description: "A dystopian novel about totalitarianism.",
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 7.99,
    rating: 4.3,
    genre: "Romance",
    description: "A romantic novel of manners.",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 9.99,
    rating: 4.2,
    genre: "Fiction",
    description: "A tale of wealth and tragedy.",
  },
  {
    id: 5,
    title: "Dune",
    author: "Frank Herbert",
    price: 12.99,
    rating: 4.7,
    genre: "Science Fiction",
    description: "A sci-fi epic about politics and power.",
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 9.49,
    rating: 4.1,
    genre: "Fiction",
    description: "A story of teenage rebellion and alienation.",
  },
  {
    id: 7,
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 10.99,
    rating: 4.4,
    genre: "Dystopian",
    description:
      "A thought-provoking novel about a controlled, utopian society.",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 11.99,
    rating: 4.9,
    genre: "Fantasy",
    description: "The epic tale of Bilbo Baggins' journey in Middle-earth.",
  },
  {
    id: 9,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: 9.99,
    rating: 4.8,
    genre: "Fantasy",
    description: "The beginning of a young wizard's adventures at Hogwarts.",
  },
  {
    id: 10,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 8.49,
    rating: 4.6,
    genre: "Philosophical Fiction",
    description: "A magical story about following your dreams.",
  },
  {
    id: 11,
    title: "Moby Dick",
    author: "Herman Melville",
    price: 10.49,
    rating: 4.0,
    genre: "Adventure",
    description: "An epic sea journey in pursuit of the great white whale.",
  },
  {
    id: 12,
    title: "The Road",
    author: "Cormac McCarthy",
    price: 7.99,
    rating: 4.5,
    genre: "Post-Apocalyptic",
    description: "A haunting tale of survival in a bleak, desolate world.",
  },
  {
    id: 13,
    title: "The Book Thief",
    author: "Markus Zusak",
    price: 8.99,
    rating: 4.7,
    genre: "Historical Fiction",
    description: "A powerful story narrated by Death, set in Nazi Germany.",
  },
  {
    id: 14,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 14.99,
    rating: 4.8,
    genre: "Non-Fiction",
    description: "A fascinating exploration of human history and evolution.",
  },
  {
    id: 15,
    title: "The Art of War",
    author: "Sun Tzu",
    price: 6.99,
    rating: 4.2,
    genre: "Philosophy",
    description: "An ancient treatise on military strategy and tactics.",
  },
];
